export const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST'
export const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS'
export const FETCH_BEER_ERROR = 'FETCH_BEER_ERROR'

export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'
export const FECTH_SEARCH_ERROR = 'FECTH_SEARCH_ERROR'